### ISSUE TITLE
As a Data-drift dev, I have a clearer interface for function `store_metric()`

### ISSUE THREAD

**Issue by marcbllv** [data-drift/data-drift#135]
### Issue

`datagit.github_connector.store_metric()` function has a strange behavior regarding opening or merging PRs:

- If assignees is set, then a PR is opened
- If not, no PR is open, but:
  - if branch happens to be set to `main`, then changes are pushed to main branch and can be used in future drift computation
  - if branch is not set / set to something else, drift will be simply stored in a branch

We have 3 different behaviors (related to "how to handle changes?") that are controlled by 2 params that seem not really related.

Also having changes pushed in `main` branch is nice, but what's be nicer would be having a PR opened and then automatically merged --> better for keeping track of who changed what

### Proposal

- New param: `merge_policy` = [ `no_pr`, `open_pr`, `auto_merge_pr` ]
  - `no_pr` -> Simply push changes to a branch, and do nothing more
  - `open_pr` -> Same as no_pr but also open a PR
  - `auto_merge_pr` -> Same as open_pr but immediately auto-merge it
- We keep param `assignee`, but if it's None/empty list then -> PR is opened with no assignee
- We keep param `branch`, it simply controls where things are pushed

We could use an Enum for that

```python
class MergePolicy(Enum):
    NoPR = "NoPR"
    OpenPR = "OpenPR"
    AutoMergePR = "AutoMergePR"


github_connector.store_metric(
    ghClient=Github(github_api_token),
    dataframe=dataframe,
    merge_policy=MergePolicy.AutoMergePR,
    assignees=[],
    branch=branch,
)
```

**Comment by Samox** [comment]
This API looks good, happy to help to develop this :D
