### ISSUE TITLE
AAU, I can see the drift on a metric between 2 given dates

### ISSUE THREAD

**Issue by Lucasdvrs** [data-drift/data-drift#201]
### Why we need this
Users want to compare two metrics in time and see by how much/why it has drifted. Use cases: compare with the previous investor update or board pack.

> je veux comparer le MRR EoP d’aujourd’hui à celui qui a été communiqué au board en juillet 2023 (et pas par rapport au dernier main ou depuis la 1e historisation)

### Solution Design 
_tbd_

### Task
_tbd_

**Comment by Samox** [comment]
Done with https://github.com/data-drift/data-drift/pull/287
